NEP29 Compliance
pyvista/pytest-pyvista pull request #85
Opened 2023-09-26 21:21 UTC by bjlittle

This PR adopts the [NEP29 Drop Schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule) for minimum supported versions of `python` and `numpy`.

When working on #84 I noticed that the PyPI versions were wrong for `pytest-pyvista`. Turns out, incorrect syntax (probably migrated from `setup.py` or `setup.cfg`) was used to specify the required `python` version for the package; minor fixed sorted this.

Went the extra mile and also configured the  [validate-pyproject](https://github.com/abravalheri/validate-pyproject) pre-commit hook to automate confidence in the `pyproject.toml`.

2023-09-26 21:30 UTC, tkoyama010 approved these changes
Thanks! I wondered the same thing. About adding `validate-pyproject`, also ask the @MatthewFlamm if it would be useful as it would increase run time. If it is adopted here, please consider sending an additional PR to `pyvista/pyvista`.

2023-09-26 21:38 UTC, bjlittle commented
> Thanks! I wondered the same thing. About adding `validate-pyproject`, also need to ask the @MatthewFlamm if it would be useful to add as it would increase run time. If it is adopted here, please consider sending an additional PR to [pyvista/pyvista](https://github.com/pyvista/pyvista) too.

@tkoyama010 Cool, thanks.

Although, it seems to be a relatively snappy pre-commit hook. I'm not seeing much difference in runtime or resources being used.

2023-09-26 22:57 UTC, MatthewFlamm commented
Since this package is required for testing pyvista, we can't drop python 3.8 support without dropping it in PyVista.  We should probably move the discussion there.

2023-09-26 23:04 UTC, tkoyama010 commented
Oh, I see. I totally forgot this project was used in PyVista😅.

2023-09-26 23:13 UTC, tkoyama010 commented
I started https://github.com/pyvista/pyvista/discussions/4960 . Let's discuss it there!

2023-09-26 23:14 UTC, tkoyama010 requested changes
Keep this while we discuss it.

2023-09-28 17:20 UTC, bjlittle commented
@MatthewFlamm and @tkoyama010 

Whilst we await a decision on this one, I'm going to put the pull-request into `draft` to ensure it's not merged 👍

2025-07-14 00:38 UTC, akaszynski commented
Out of date, dropping. Thanks for pointing this out @bjlittle.

2025-07-14 00:38 UTC, closed without merging